package tserviceClases;
// Generated 19/02/2015 11:32:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExperienciaLaboral generated by hbm2java
 */
@Entity
@Table(name="Experiencia Laboral")
public class ExperienciaLaboral  implements java.io.Serializable {


     private Integer id;
     private String entidad;
     private Date fechaActualizacion;
     private String comentario;
     private List<Persona> personas = (List<Persona>) new HashSet(0);

    public ExperienciaLaboral() {
    }

	
    public ExperienciaLaboral(String entidad, Date fechaActualizacion, String comentario) {
        this.entidad = entidad;
        this.fechaActualizacion = fechaActualizacion;
        this.comentario = comentario;
    }
    public ExperienciaLaboral(String entidad, Date fechaActualizacion, String comentario, List<Persona> personas) {
       this.entidad = entidad;
       this.fechaActualizacion = fechaActualizacion;
       this.comentario = comentario;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Entidad", nullable=false, length=45)
    public String getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha Actualizacion", nullable=false, length=10)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    
    @Column(name="Comentario", nullable=false, length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

   
@ManyToMany(fetch = FetchType.LAZY, mappedBy = "experienciaLaborals")

    public List<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(List<Persona> personas) {
        this.personas = personas;
    }




}


