package tserviceClases;
// Generated 19/02/2015 11:32:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="Factura"
    ,catalog="coswg2"
)
public class Factura  implements java.io.Serializable {


     private Integer id;
     private Licencias licencias;
     private String referenciaPago;
     private int valor;
     private Date fecha;

    public Factura() {
    }

    public Factura(Licencias licencias, String referenciaPago, int valor, Date fecha) {
       this.licencias = licencias;
       this.referenciaPago = referenciaPago;
       this.valor = valor;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Licencias_idLicencias", nullable=false)
    public Licencias getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Licencias licencias) {
        this.licencias = licencias;
    }
    
    @Column(name="Referencia Pago", nullable=false, length=45)
    public String getReferenciaPago() {
        return this.referenciaPago;
    }
    
    public void setReferenciaPago(String referenciaPago) {
        this.referenciaPago = referenciaPago;
    }

    
    @Column(name="Valor", nullable=false)
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


